project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

commit_message: |
  i18n: %language% translations from Crowdin
  
  [skip ci]
append_commit_message: false

files:
  - source: '/**/lang/en_us.json'
    translation: '/**/lang/%locale_with_underscore%.json'
