plugins {
    alias(libs.plugins.moddev)
    alias(libs.plugins.fletchingtable.neoforge)
    id("freecam.loaders")
}

fletchingTable {
    accessConverter.register(sourceSets.main) {
        // During processResources, Fletching Table will exclude this file
        // and generate a META-INF/accesstransformer.cfg from it
        add("freecam.accesswidener")
    }
}

neoForge {
    enable {
        version = meta.deps["neoforge"]
    }
}

dependencies {
    "me.shedaniel.cloth:cloth-config-neoforge:${meta.deps["cloth"]}".also { old ->
        val new = modLibraries.clothConfig.maven.coordinate
        require(old == new) {
            "${project.path} old $old new $new"
        }
        api(new)
        jarJar(implementation(new) as Any)
    }
}

neoForge {
    // Use the accesstransformer generated by Fletching Table
    accessTransformers.from(tasks.processResources.map {
        it.destinationDir.resolve("META-INF/accesstransformer.cfg")
    })
    validateAccessTransformers = true

    runs {
        register("client") {
            client()
            ideName = "NeoForge Client (${project.path})"
        }
//        register("server") {
//            server()
//            ideName = "NeoForge Server (${project.path})"
//        }
    }

    require((modLibraries.parchment == null) == (meta.deps.orNull("parchment") == null))
    modLibraries.parchment?.also {
        parchment {
            minecraftVersion = it.maven.name.substringAfter('-')
            mappingsVersion = it.maven.version
            meta.parchment { mappings, mc ->
                require(mc == it.maven.name.substringAfter('-'))
                require(mappings == it.maven.version)
            }
        }
    }

    mods {
        register(meta.id) {
            sourceSet(sourceSets.main.get())
        }
    }
}

sourceSets.main {
    resources.srcDir("src/generated/resources")
}

tasks.register<Copy>("buildAndCollect") {
    group = "build"
    from(tasks.jar.map { it.archiveFile })
    into(rootProject.layout.buildDirectory.file("libs/${meta.version}"))
    dependsOn(tasks.build)
}

tasks.named("createMinecraftArtifacts") {
    dependsOn(":neoforge:${project.name}:processResources")
}

tasks.processResources {
    filesMatching(listOf("META-INF/mods.toml", "META-INF/neoforge.mods.toml")) {
        expand(commonExpansions)
    }

    filesMatching("freecam-neoforge.mixins.json") {
        expand(commonJsonExpansions)
    }

    filesMatching("pack.mcmeta") {
        expand(commonJsonExpansions)
    }

    inputs.properties(commonExpansions)
}

publisher {
    artifact.set(tasks.named("jar"))
}
