modLoader="javafml"
loaderVersion="[48,)"
issueTrackerURL="https://github.com/wagyourtail/jsmacros"
license = "MPL-2.0"

[[mods]]
modId = "freecam"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
    This is an example description! Tell everyone what your mod is about!
'''
logoFile="icon.png"

[[dependencies.freecam]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2]"
ordering="NONE"
side="BOTH"