name: Build

on:
  push:

# Only allow running one build job at a time to optimise cache hits
concurrency:
  group: builds

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: microsoft
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

        # Upload all jars as `jars.zip`
        # TODO consider uploading individually, using a build matrix
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: build/lib
          retention-days: 90
