name: Crowdin (Upload)

on:
  workflow_dispatch: # Allow running manually
  # Run when a lang file is modified
  push:
    branches:
      - main
      - i18n/test
    paths:
      - '/**/lang/*.json'

# When this workflow runs, it will kill any in-progress workflows with the same group
concurrency:
  group: crowdin
  cancel-in-progress: true

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin upload
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
          crowdin_branch_name: ${{ env.BRANCH_NAME }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}