name: Crowdin (Upload Translations)

on:
  workflow_dispatch: # Allow running manually
## (Disable automatic runs for now)
#  push: # Run when a non-en_us lang file is modified on the main branch
#    branches:
#      - main
#    paths:
#      - '**/lang/*.json'
#      - '!**/lang/en_us.json'

# Kill any currently running workflows in the 'crowdin' group before running this.
# Will break if on.push gets enabled, because this will run concurrently with upload-sources
concurrency:
  group: crowdin
  cancel-in-progress: true

jobs:
  upload_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Translations
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: true
          download_translations: false
          crowdin_branch_name: ${{ github.ref_name }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}